# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'ShiftLibra' do

    use_frameworks!

    inhibit_all_warnings!

  # Pods for ShiftLibra

    pod 'SnapKit', '~> 3.0.0'

    pod 'AFNetworking'

    pod 'YYModel'

    pod 'pop'

    pod 'FMDB'

    pod 'FoldingCell', '~> 2.0.3'

    pod 'TPKeyboardAvoiding'

end
