# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'ShiftLibra' do

    use_frameworks!

    inhibit_all_warnings!

  # Pods for ShiftLibra

    pod 'SnapKit'

    pod 'AFNetworking'

    pod 'YYModel'

    pod 'pop'

    pod 'FMDB'

    pod 'FoldingCell'
    
    pod 'TPKeyboardAvoiding'

end
